site:
  title: DDM Documentation
  start_page: ddm::index.adoc
content:
  sources:
    - url: ../
      branches: [main, develop, participant-continuation]
      version: true
      start_path: docs
ui:
  bundle:
    url: ./ui/ui-bundle.zip
    snapshot: true
