# Runs a build test every time a commit is pushed to branch 'main'.

name: Test and Publish Python Package

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.10.4]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_project/requirements.txt
      - name: Run Tests
        run: |
          python test_project/manage.py test ddm

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Generate new setup.cfg
        run: bash version_bump.sh
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Dispatch signal to DDL
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_WORKFLOW_TOKEN }}
          repository: uzh/ddl
          event-type: new-ddm-version
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
